### PR TITLE
49202 backend [ python ] Upgrade Python version to 3.9.

### PR DESCRIPTION
**Pull request by andrey-usov**
# Problem

The platform runs on a version of its core technology that stopped receiving security updates in
October 2024. Every month on an unsupported version adds risk: newly discovered vulnerabilities are
never fixed, and we have no vendor to fall back on. It also blocks us — an increasing number of the
tools and libraries we depend on no longer ship versions compatible with what we run, so routine
updates and new integrations get harder and slower over time. Enterprise customers ask about
supported runtimes during security reviews, and the current answer is not a good one.

This change moves the product onto a supported version. Nothing that customers see or do changes.

# Fix / Solution

Upgrade the backend runtime from Python 3.8.20 to 3.9.25 without touching application code.

- Base image: `python:3.8.20-bullseye` → `python:3.9.25-bookworm`. The `bullseye` variants of
  `library/python` stop at 3.9.23, so the final 3.9 patch requires Debian 12. This also moves the
  image from OpenSSL 1.1.1 to OpenSSL 3.0, which is the main risk area for outgoing TLS.
- Python constraint in `pyproject.toml`: `~3.8` → `~3.9`. A mismatch here fails `poetry install`
  at image build time — this is what broke the staging deploy during the 3.7 → 3.8 upgrade.
- `uvloop` 0.14.0 → 0.15.3 and `httptools` 0.1.1 → 0.1.2. Both are mandatory, not optional:
  `UvicornWorker` forces them via `CONFIG_KWARGS`, and the worker refuses to start without them.
  Neither old version builds on Python 3.9.
- `psycopg2-binary` 2.8.5 → 2.8.6. Version 2.8.5 ships no cp39 wheels, so it would be compiled
  from source on every build. Version 2.9 and above is intentionally avoided: it is incompatible
  with Django 2.2 when `USE_TZ = True` and raises an `AssertionError` on timezone-aware queries
  (Django ticket #32856).
- `websockets` stays at 8.1. It can only be upgraded together with `uvicorn`, which is out of
  scope here.
- `poetry.lock` regenerated with `--no-update` so the diff stays minimal: exactly the three
  packages above changed, plus two Python 3.8 backports dropped (`importlib-resources`,
  `pkgutil-resolve-name`). A plain `poetry lock` pulls 60+ transitive packages to their latest
  versions, which is not acceptable in this change.
- `ruff` `target-version` deliberately left at `py38`. Switching it to `py39` enables the PEP 585
  rules and produces an autofix diff across 115 files on top of a runtime upgrade. Typing
  modernization is planned as a single pass when we move to 3.10.
- Documentation and local-tooling markers synced: `.python-version`, `.pre-commit-config.yaml`,
  `backend/README.md` (both the Linux/pyenv and the Windows installer instructions).

**Coordination requirement.** Jenkins renders its own Dockerfile from a template in the
`pneumatic-deploy-config` repository. That template must be updated to Python 3.9 in a separate PR.
Until both are merged, staging cannot be deployed from any branch — a red `backend-staging` job
complaining about the Python version is the expected symptom, not an incident.

# Release notes

No user-facing changes. This is an internal runtime upgrade that moves the backend onto a supported
Python version and keeps behaviour identical.

# Changes

## API

No endpoints added, removed or changed. No serializers, permissions or business logic touched —
the diff contains no application code at all.

Areas QA should treat as affected, because the binaries underneath them were rebuilt:

- **Outgoing TLS (highest priority).** The OS change brings OpenSSL 3.0, which disables TLS 1.0/1.1
  and raises the default security level. Everything that makes an outbound HTTPS or SMTP
  connection is affected: SMTP mail, outgoing webhooks, all SSO providers, Stripe, Customer.io,
  Segment, OpenAI, Slack, Firebase, reCAPTCHA, Sentry.
- **Database driver.** `psycopg2` was rebuilt and bumped. It is responsible for converting
  `timestamptz` to `datetime` and for `Decimal` handling, so dates, sorting by due date and
  billing amounts are the places where a silent mismatch would show up.
- **WebSocket transport.** New `uvloop` event loop and rebuilt `httptools` HTTP parser sit under
  every request and every realtime notification.
- **Celery.** Worker and beat run on the same new interpreter.

## Web-client

No changes.

# Test cases

## API

| Authorization | Test case | Expected result |
| --- | --- | --- |
| Not required | Send a request without a token to any protected endpoint | 401, unchanged error body |
| User | Sign in, then request the task list and the account user list | 200, payload structure identical to the previous release |
| Not required | Sign in with invalid credentials, sending `Accept-Language` as `en`, `de`, `fr`, `es` in turn | 403 each time, error text returned in the requested language |
| Owner | Trigger a transactional email (registration confirmation) with the SMTP provider enabled | Mail is delivered over TLS; no `SSLError` or `UNSUPPORTED_PROTOCOL` in the logs |
| Owner | Subscribe an external endpoint to workflow completion, then complete a workflow | Endpoint receives the POST; JSON structure matches the previous release |
| Not required | Sign in through Google, Microsoft, Auth0 and Okta | Login succeeds for each provider; TLS handshake to the provider does not fail |
| Owner | Complete a Stripe checkout with a test card, then change and cancel the plan | Subscription state and plan limits update; webhooks are accepted |
| User | Create a workflow with a due date in a non-default timezone, then list and sort by due date | Date and time displayed match the previous release; ordering is correct |
| User | Request a list endpoint with pagination and ordering parameters | 200; page size, offset and ordering respected |
| Owner | Attach a file to a task, download it, then delete it | File uploads, downloads byte-identical, and is unavailable after deletion |
| Admin | Raise a test exception in a request and inside a Celery task | Both appear in Sentry with correct stack traces |
| Not required | Send a Stripe webhook with an invalid signature | 400, subscription unchanged, attempt logged |
| User | Request AI template generation while the provider is unreachable | Clear error, not a 500; the task does not hang |
| Owner | Complete a workflow while the subscribed webhook endpoint is down | Retries are scheduled, workflow still completes |
| Admin | Open the Django admin: model list, a changelist and an object page | Pages render, static assets load |

## Web-client

This is a runtime change with no rendering impact, so cross-browser and mobile coverage is not
required.

| Browser | Device | Authorization | Test scenario | Expected result |
| --- | --- | --- | --- | --- |
| Chrome | Desktop | User | Keep the app open, have another user assign a task | Realtime notification arrives without a page refresh |
| Chrome | Desktop | User | Disconnect the network for 30 seconds with the app open, then restore it | Client reconnects; missed events are not duplicated |
| Chrome | Desktop | User | Deploy a new backend version while the app is open | Session recovers after the connection drops; no error screen |
| Chrome | Desktop | User | Register, then confirm the account from the email | Registration completes and the confirmation email arrives |
| Chrome | Desktop | Owner | Open the billing page and change the plan | Plan and limits update in the interface |
| Chrome | Mobile | User | Allow push notifications, then receive a task assignment | Push is delivered and opens the correct task |

# Verification already performed

- Full test suite on 3.9.25: **6161 passed, 0 failed** — the same test count as the 3.8.20 run.
- Images build for `linux/amd64` and `linux/arm64`; arm64 built under emulation in 1424 s.
- Full stack brought up on the new image under the Production configuration: WebSocket connect,
  heartbeat, delivery through Redis from a separate container, reconnect after an abrupt drop,
  graceful gunicorn reload with no orphaned tasks, Celery worker responding, all four locales
  returned over HTTP, Django admin pages rendering.
- Not covered locally and left to QA: every external integration listed under **Changes → API**,
  since all outbound calls are mocked in the test suite.

---

> [!NOTE]
> **Medium Risk**
> Debian bookworm brings OpenSSL 3.0 (outbound TLS behavior) and rebuilt DB/ASGI binaries; scope is infra-only but those layers sit under all HTTP, WebSocket, Celery, and PostgreSQL traffic.
> 
> **Overview**
> **Upgrades the backend from Python 3.8.20 to 3.9.25** with no application code changes—only runtime, packaging, and developer tooling.
> 
> The Docker base image moves from `python:3.8.20-bullseye` to `python:3.9.25-bookworm`, and Poetry’s constraint becomes `~3.9`. Local markers (`.python-version`, pre-commit default Python, `backend/README.md`) are aligned with 3.9.
> 
> **Native/ASGI dependencies** are bumped so the stack builds and starts on 3.9: `psycopg2-binary` 2.8.5→2.8.6, `uvloop` 0.14.0→0.15.3, and `httptools` 0.1.1→0.1.2, with a regenerated `poetry.lock` (including removal of 3.8-only backports like `importlib-resources` and `pkgutil-resolve-name`).
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit fdca610a07f426a0b7c30bd75526a4f0e23468a0. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

> [!NOTE]
> ### Upgrade backend Python version from 3.8 to 3.9
> - Updates the Docker base image from `python:3.8.20-bullseye` to `python:3.9.25-bookworm` in [backend/Dockerfile](https://github.com/pneumaticapp/pneumaticworkflow/pull/349/files#diff-fed51f49a9f26cb93cc870efdc9419d425b9422354ae41bb651c3333c8bff486)
> - Sets Python requirement to `~3.9` in [backend/pyproject.toml](https://github.com/pneumaticapp/pneumaticworkflow/pull/349/files#diff-9f2cf60079756e94b31dbaeb145297215236d3c0135647163c2e51b80fd81551) and bumps `psycopg2-binary` to 2.8.6, `uvloop` to 0.15.3, and `httptools` to 0.1.2
> - Updates [pre-commit config](https://github.com/pneumaticapp/pneumaticworkflow/pull/349/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9) and [pyenv version](https://github.com/pneumaticapp/pneumaticworkflow/pull/349/files#diff-652bad7c1002badcf13f8de3a5096c2724ce54ae36cd68a21ad280547dff8e87) to Python 3.9, and revises [backend/README.md](https://github.com/pneumaticapp/pneumaticworkflow/pull/349/files#diff-a54d2dad1be5eea9e70f8514ae65d89b65357120a312bfb9f644ddeb1844ca0d) setup instructions accordingly
> - Behavioral Change: base container switches from Debian bullseye to Debian bookworm; dependency version bumps may affect runtime behavior of `psycopg2-binary`, `uvloop`, and `httptools`
>
> 
>
> <details>
> <summary>📊 <a href="https://app.macroscope.com">Macroscope</a> summarized fdca610. 4 files reviewed, 1 issue evaluated, 0 issues filtered, 1 comment posted</summary>
>
> ### 🗂️ Filtered Issues
>
> </details>
>

### CODE REVIEW

File: backend/Dockerfile [hunk 1]
```diff
@@ -1,4 +1,4 @@
-FROM python:3.8.20-bullseye
+FROM python:3.9.25-bookworm
```
[the remark this answers is not in the document]
Comment (andrey-usov) [reply backend/Dockerfile:1]: Valid point, and it is already tracked as risk 8 in the upgrade plan: Python 3.9 reached EOL on 2025-10-31, so this PR is explicitly an intermediate step rather than a final destination.

`python:3.11-bookworm` is not reachable in this PR, though. I verified the blockers instead of assuming them:

**1. Celery 4.4.7 cannot even be imported on 3.11.** `vine.five` does `from inspect import formatargspec, getargspec`, and `inspect.formatargspec` was removed in Python 3.11:

```
ImportError: cannot import name 'formatargspec' from 'inspect'
```

Celery 4.4.7 pins `kombu >=4.6.10,<4.7`, `billiard <4.0` and `vine 1.3.0`, so unblocking it means replacing the whole broker stack with Celery 5 — a separate task.

**2. The pinned native dependencies have no wheels above cp39, and their sdists do not compile on 3.11.** `uvloop 0.15.3`, `httptools 0.1.2` and `psycopg2-binary 2.8.6` publish cp38/cp39 wheels only, and `pip install --no-binary :all:` fails to build `uvloop` and `httptools` on 3.11.

**3. `psycopg2-binary` cannot be bumped to a version that ships 3.10/3.11 wheels.** Django 2.2 is incompatible with psycopg2 >= 2.9: `tzinfo_factory` receives a `timedelta` instead of int minutes, so `utc_tzinfo_factory` raises `AssertionError: database connection isn't set to UTC` on every `timestamptz` query. Django closed [#32856](https://code.djangoproject.com/ticket/32856) as wontfix for the 2.2 branch and documented `psycopg2 < 2.9`. This project runs Django 2.2.28 with `USE_TZ = True` and `TIME_ZONE = 'UTC'`, so all three conditions hold.

Python 3.10 does not help either — same wheel wall, plus it reaches EOL in October 2026. So 3.9.25 is the highest runtime reachable without upgrading Celery and Django first, and both are tracked as separate tasks. A follow-up to 3.10+ is planned within 6 months, together with the `websockets` + `uvicorn` bump and the PEP 585 typing migration.

**Review by pneumojoseph — APPROVED** [review]

**Review by timofey-zeph — APPROVED** [review]
